import ThemeChecker from "@/components/Dashboard/ThemeChecker";
import "./globals.css";
import "./index.css"
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={"bg-light-v-1 dark:text-light-v-1  font-dm dark:bg-dark-v-2"}>
        {children}
        <ThemeChecker />
      </body>
    </html>
  );
}
